class FakeEMTRepository:
    """Fake repository for testing purposes."""

    async def get_stop_info(self, stop_id): ...
    async def get_arrivals(self, stop_id): ...
    async def get_nearby_stops(self, lat, lon, radius): ...
